export const CATEGORY_ICON_OPTIONS = [
  "briefcase-outline",
  "cash-outline",
  "wallet-outline",
  "card-outline",
  "trending-up-outline",
  "restaurant-outline",
  "car-outline",
  "home-outline",
  "medical-outline",
  "school-outline",
  "bag-outline",
  "gift-outline",
  "game-controller-outline",
  "airplane-outline",
  "fitness-outline",
  "phone-portrait-outline",
  "book-outline",
  "sparkles-outline",
  "construct-outline",
  "ellipsis-horizontal-outline",
] as const;

export const CATEGORY_COLOR_OPTIONS = [
  "#F97316",
  "#3B82F6",
  "#F59E0B",
  "#22C55E",
  "#EC4899",
  "#14B8A6",
  "#0EA5E9",
  "#A855F7",
  "#EF4444",
  "#06B6D4",
  "#64748B",
  "#84CC16",
] as const;
